### ISSUE TITLE
Add custom song page

### ISSUE THREAD

**Issue by Briesmas** [cory2067/gtsosu#141] opened 2022-10-04 21:57 UTC
Add a new page to list all the custom songs made for GTS with links to socials
Maybe it's possible to add soundcloud preview player? Idk how that works

**Comment by cory2067** [comment] 2022-10-04 21:58
Duplicate of #44

**Comment by Chupalika** [comment] 2023-06-12 06:59
done in #175

**Closed by Chupalika** 2023-06-12 06:59 UTC
Labels: enhancement
